name: Test

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: '45 23 1 * *'  # Monthly check

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.0', '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7',
                '3.0', '3.1', '3.2',
                head ]
    runs-on: ubuntu-latest
    name: Unit test with Ruby ${{ matrix.ruby }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: |
          bundle exec rake spec
